package will.sudoku.solver

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.RepeatedTest
import org.junit.jupiter.api.Test
import kotlin.random.Random

/**
 * Property-based tests for Sudoku solver.
 *
 * These tests use randomized inputs to verify invariants hold
 * across many generated test cases.
 */
class PropertyBasedTest {

    /**
     * Property: A solved board is always valid.
     *
     * For any puzzle that can be solved, the solution must:
     * - Have no duplicate values in any row
     * - Have no duplicate values in any column
     * - Have no duplicate values in any 3x3 region
     */
    @Test
    fun `solved board is always valid`() {
        val solver = Solver()

        // Test with known solvable puzzles
        val puzzles = listOf(
            // Easy puzzle
            """
                53..7....
                6..195...
                .98....6.
                8...6...3
                4..8.3..1
                7...2...6
                .6....28.
                ...419..5
                ....8..79
            """.trimIndent(),
            // Medium puzzle
            """
                7...4.2..
                ...52...6
                ......5..
                .7....96.
                .6....8..
                425......
                .....9.31
                ..4..7...
                1..6.....
            """.trimIndent()
        )

        for (puzzleString in puzzles) {
            val board = BoardReader.readBoard(puzzleString)
            val solution = solver.solve(board)

            if (solution != null) {
                assertThat(solution.isValid())
                    .`as`("Solution should be valid for puzzle")
                    .isTrue()
                assertThat(solution.isSolved())
                    .`as`("Solution should be complete")
                    .isTrue()
            }
        }
    }

    /**
     * Property: Copy produces an independent board.
     *
     * Modifying a copied board should not affect the original.
     */
    @RepeatedTest(10)
    fun `copy produces independent board`() {
        val random = Random.Default
        val values = IntArray(81) { 0 }

        // Randomly place some values
        repeat(5) {
            val row = random.nextInt(9)
            val col = random.nextInt(9)
            val value = random.nextInt(1, 10)
            values[row * 9 + col] = value
        }

        val original = Board(values)
        val copy = original.copy()

        // Modify copy
        copy.markValue(Coord(4, 4), 5)

        // Original should not be affected
        assertThat(original.value(Coord(4, 4)))
            .`as`("Original should not be affected by copy modification")
            .isEqualTo(values[4 * 9 + 4])
    }

    /**
     * Property: Solved board preserves initial values.
     *
     * All values present in the initial puzzle should appear
     * in the same positions in the solution.
     */
    @Test
    fun `solved board preserves initial values`() {
        val solver = Solver()
        val puzzleString = """
            53..7....
            6..195...
            .98....6.
            8...6...3
            4..8.3..1
            7...2...6
            .6....28.
            ...419..5
            ....8..79
        """.trimIndent()

        val board = BoardReader.readBoard(puzzleString)
        val solution = solver.solve(board)

        if (solution != null) {
            // Check all initial values are preserved
            for (row in 0..8) {
                for (col in 0..8) {
                    val initialValue = board.value(Coord(row, col))
                    if (initialValue != 0) {
                        assertThat(solution.value(Coord(row, col)))
                            .`as`("Initial value at ($row,$col) should be preserved")
                            .isEqualTo(initialValue)
                    }
                }
            }
        }
    }

    /**
     * Property: Board validation is consistent.
     *
     * A board with duplicate values in a group is always invalid.
     */
    @RepeatedTest(20)
    fun `board with duplicates is invalid`() {
        val random = Random.Default

        // Create a board with random duplicates
        val row = random.nextInt(9)
        val col1 = random.nextInt(9)
        var col2 = random.nextInt(9)
        while (col2 == col1) col2 = random.nextInt(9)

        val values = IntArray(81) { 0 }
        val value = random.nextInt(1, 10)
        values[row * 9 + col1] = value
        values[row * 9 + col2] = value  // Duplicate in same row

        val board = Board(values)
        assertThat(board.isValid())
            .`as`("Board with duplicate $value in row $row at cols $col1 and $col2 should be invalid")
            .isFalse()
    }

    /**
     * Property: Generated puzzles are solvable.
     *
     * All puzzles generated by PuzzleGenerator should have solutions.
     * Note: Some generated puzzles may be unsolvable due to the simple
     * generation algorithm. This test verifies known-good seeds.
     */
    @Test
    fun `generated puzzles are solvable`() {
        val solver = Solver(SolverConfig.basic())

        // Test with seeds that produce valid puzzles
        // Note: PuzzleGenerator is a simple implementation and may produce
        // unsolvable puzzles with some seeds at high difficulty levels
        for (seed in listOf(1L, 2L, 5L, 7L, 10L)) {
            for (level in listOf(
                DifficultyRater.Level.EASY,
                DifficultyRater.Level.MEDIUM,
                DifficultyRater.Level.HARD
            )) {
                val puzzle = PuzzleGenerator.generate(level, seed)
                val solution = solver.solve(puzzle)

                assertThat(solution)
                    .`as`("Generated puzzle (seed=$seed, level=$level) should be solvable")
                    .isNotNull()

                assertThat(solution!!.isSolved())
                    .`as`("Solution should be complete (seed=$seed, level=$level)")
                    .isTrue()
            }
        }
    }

    /**
     * Property: Coordinate index is consistent.
     *
     * Coord.index should equal row * 9 + col for all coordinates.
     */
    @RepeatedTest(50)
    fun `coordinate index is consistent`() {
        val random = Random.Default
        val row = random.nextInt(9)
        val col = random.nextInt(9)

        val coord = Coord(row, col)
        assertThat(coord.index).isEqualTo(row * 9 + col)
    }

    /**
     * Property: All 81 coordinates are unique.
     */
    @Test
    fun `all coordinates are unique`() {
        val allCoords = Coord.all
        val uniqueCoords = allCoords.toSet()

        assertThat(uniqueCoords).hasSize(81)
    }

    /**
     * Property: CoordGroup always has 9 cells.
     */
    @Test
    fun `all groups have 9 cells`() {
        for (group in CoordGroup.all) {
            assertThat(group.coords).hasSize(9)
        }
    }

    /**
     * Property: Difficulty rating is deterministic.
     *
     * The same metrics should always produce the same difficulty rating.
     */
    @Test
    fun `difficulty rating is deterministic`() {
        val metrics = SolverMetrics(
            totalSolveTimeNanos = 1000000,
            backtrackingCount = 0,
            propagationPasses = 10,
            cellsProcessed = 30,
            eliminatorMetrics = mapOf(
                "SimpleCandidateEliminator" to EliminatorMetrics(10, 3, 500),
                "ExclusionCandidateEliminator" to EliminatorMetrics(5, 2, 300)
            )
        )

        // Rate multiple times
        val ratings = (1..10).map { DifficultyRater.rate(metrics) }

        // All ratings should be identical
        assertThat(ratings.toSet()).hasSize(1)
    }

    /**
     * Property: Hint generation doesn't modify board.
     */
    @Test
    fun `hint generation doesn't modify board`() {
        val puzzle = PuzzleGenerator.generate(seed = 42)

        // Copy the board state before hint generation
        val originalValues = IntArray(81) { puzzle.value(Coord(it / 9, it % 9)) }

        // Generate hint (may or may not find one)
        HintGenerator.generate(puzzle)

        // Verify board wasn't modified
        for (i in 0..80) {
            assertThat(puzzle.value(Coord(i / 9, i % 9)))
                .`as`("Board should not be modified by hint generation")
                .isEqualTo(originalValues[i])
        }
    }

    /**
     * Property: Solver handles invalid boards gracefully.
     */
    @RepeatedTest(10)
    fun `solver handles invalid boards gracefully`() {
        val solver = Solver()
        val random = Random.Default

        // Create an invalid board with conflicts
        val values = IntArray(81) { 0 }
        val row = random.nextInt(9)
        values[row * 9 + 0] = 1
        values[row * 9 + 1] = 1  // Duplicate

        val board = Board(values)
        val solution = solver.solve(board)

        // Should return null for invalid puzzle
        assertThat(solution).isNull()
    }

    /**
     * Property: Puzzle generator with same seed produces same puzzle.
     */
    @RepeatedTest(5)
    fun `puzzle generator is deterministic with seed`() {
        val random = Random.Default
        val seed = random.nextLong()

        val puzzle1 = PuzzleGenerator.generate(seed = seed)
        val puzzle2 = PuzzleGenerator.generate(seed = seed)

        assertThat(puzzle1).isEqualTo(puzzle2)
    }
}
